# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_product_on_sale'),
        ('custom', '0002_auto_20170417_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
    ]
