# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uimanagement', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
