# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uimanagement', '0004_auto_20170412_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='site',
        ),
    ]
