# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170412_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
