# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_remove_brand_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
