# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_product_on_sale'),
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('link', models.URLField(default='')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
            ],
        ),
    ]
